---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: blog-promoter-service
  name: blog-promoter-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: blog-promoter-service
  template:
    metadata:
      labels:
        app: blog-promoter-service
    spec:
      containers:
        - image: gcr.io/joshlong/blog-promoter-service
          imagePullPolicy: Always
          name: blog-promoter-service-container

          startupProbe:
            failureThreshold: 120
            periodSeconds: 120
            httpGet:
              port: 8080
              path: /actuator/health/readiness

          readinessProbe:
            failureThreshold: 120
            periodSeconds: 120
            httpGet:
              port: 8080
              path: /actuator/health/readiness

          livenessProbe:
            failureThreshold: 120
            periodSeconds: 120
            httpGet:
              port: 8080
              path: /actuator/health/liveness

          envFrom:
            - secretRef:
                name: blog-promoter-service-secrets

          resources:
            limits:
              memory: "1Gi"
            requests:
              memory: "1Gi"          