name: Deploy

env:


  APP_NAME: blog-promoter-service
  GKE_CLUSTER:   ${{ secrets.GKE_CLUSTER }}
  GCLOUD_ZONE:  ${{ secrets.GCLOUD_ZONE }}
  NS_NAME:  ${{ secrets.NS_NAME }}
  GCLOUD_SA_KEY:  ${{ secrets.GCLOUD_SA_KEY }}


  # org level
  SPRING_RABBITMQ_HOST: ${{ secrets.SOCIALHUB_MQ_HOST }}
  SPRING_RABBITMQ_PASSWORD: ${{ secrets.SOCIALHUB_MQ_PASSWORD }}
  SPRING_RABBITMQ_PORT: ${{ secrets.SOCIALHUB_MQ_PORT }}
  SPRING_RABBITMQ_USERNAME: ${{ secrets.SOCIALHUB_MQ_USERNAME }}
  SPRING_RABBITMQ_VIRTUAL_HOST: ${{ secrets.SOCIALHUB_MQ_VIRTUAL_HOST }}

  # db
  SPRING_DATASOURCE_URL: ${{ secrets.SPRING_DATASOURCE_URL }}
  SPRING_DATASOURCE_PASSWORD: ${{ secrets.SPRING_DATASOURCE_PASSWORD }}
  SPRING_DATASOURCE_USERNAME: ${{ secrets.SPRING_DATASOURCE_USERNAME }}

  # socialhub client
  SOCIALHUB_JOSHLONG_CLIENT_KEY_SECRET: ${{ secrets.SOCIALHUB_JOSHLONG_CLIENT_KEY_SECRET }}
  SOCIALHUB_JOSHLONG_CLIENT_KEY : ${{ secrets.SOCIALHUB_JOSHLONG_CLIENT_KEY }}

  # artifactory
  ARTIFACTORY_USERNAME: ${{ secrets.ARTIFACTORY_USERNAME }}
  ARTIFACTORY_PASSWORD: ${{ secrets.ARTIFACTORY_PASSWORD }}

on:
  push:
    branches: [ main ]

jobs:
  build-and-deploy:

    permissions:
      contents: 'read'
      id-token: 'write'

    name: Setup and Deploy

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: "Setup PATH"
        run: |
          P="${GITHUB_WORKSPACE}/bin"
          mkdir -p $P
          echo "${P}" >> $GITHUB_PATH

      - uses: 'google-github-actions/auth@v0'
        with:
          credentials_json: '${{ secrets.GCLOUD_SA_KEY }}'

      - id: 'get-credentials'
        uses: 'google-github-actions/get-gke-credentials@v1'
        with:
          cluster_name: '${{ env.GKE_CLUSTER  }}'
          location: '${{ env.GCLOUD_ZONE }}'

      - run: |
          gcloud config set project $GCLOUD_PROJECT 
          gcloud --quiet auth configure-docker
          kubectl get pods


      - uses: actions/setup-java@v3
        with:
          distribution: 'adopt'
          java-version: 17

      - name: Deploy
        run: |
          kubectl get ns/$NS_NAME || kubectl create ns $NS_NAME 
          kubectl config set-context --current --namespace=$NS_NAME
          kubectl config view --minify | grep namespace: && echo "found the namespace.."

          cd $GITHUB_WORKSPACE
          export ROOT_DIR=$GITHUB_WORKSPACE
          ./deploy/deploy.sh
